title: Scala user Groups
author: Jean Helou
subscribe_rss: /atom.xml


#paginate: 5          # Posts per page on the blog index
#paginate_path: page/:num # Pagination dir settings
titlecase: true       # Converts page and post titles to titlecase
excerpt_separator: <!--more-->
excerpt_link: ...
highlighter: pygments
markdown: redcarpet
redcarpet:
    extensions:
    - fenced_code_blocks
    - strikethrough
    - autolink
    - footnotes
    - smart

# # ----------------------- #
# #   3rd Party Settings    #
# # ----------------------- #
